language: node_js

node_js:
  - '12'
  - '10'

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-setuptools python3-pip
  - pip install --upgrade pip
  - pip3 install "localstack[full]" --user localstack
  - SERVICES=sns DEBUG=1 localstack start --host & sleep 20

install:
  - docker-compose up -d
  - npm install

script:
  - npm test

env:
  global:
    - KAFKA_LOG_LEVEL=5
