language: node_js

node_js:
  - '12'
  - '10'

python:
  - '3.7'

before_install:
  - pip install "localstack[full]" --user localstack
  - SERVICES=sns DEBUG=1 localstack start --host & sleep 20

install:
  - docker-compose up -d
  - npm install

script:
  - npm test

env:
  global:
    - KAFKA_LOG_LEVEL=5
