language: node_js

node_js:
  - '14'
  - '12'
  - '10'

install:
  - docker exec ${runner.containerId} \
    /bin/sh -c "ip -4 route list match 0/0 | awk '{print $3" host.docker.internal"}' >> /etc/hosts"
  - docker-compose up -d
  - npm install

script:
  - npm test

env:
  global:
    - KAFKA_LOG_LEVEL=5
